---
name: Testing and Linting
on: [push]

jobs:
  test:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Hadolint linting
        uses: brpaz/hadolint-action@master
